### ISSUE TITLE
debian 9 使用不方便

### ISSUE THREAD

**Issue by fearlessshi** [leitbogioro/SSR.Go#12]
可以使用了。有一些问题：
怎么卸载？
每次修改配置之后都要返回主界面。
混淆模式配置已完成！

0.返回上一级
1.更改密码
2.更改端口
3.更改加密方式
4.更改协议
5.更改混淆模式
按数字键选择功能，按回车键退出

请选择： root@chuyin002:~#

**Comment by fearlessshi** [comment]
cat: /etc/redhat-release: No such file or directory
curl: option -: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by leitbogioro** [comment]
这三串代码是安装的时候，检查是否为centos系统用的，在apt包管理的linux系统上执行，虽然会提示有问题，但不影响使用
