### ISSUE TITLE
关于PVE的centos7 提示不受支持问题

### ISSUE THREAD

**Issue by ntgeralt** [leitbogioro/SSR.Go#18]
你好，我在ProXmox VE 虚拟机开的centos 7主机，执行bash -c "$(curl -fsSL https://git.io/fNpuL)"，提示操作系统不受支持。

你看看

**Comment by ntgeralt** [comment]
我换成debian9则可以了。但装了N久啊，代码包含apt-get upgrade吗？感受不到GO的清爽。

**Comment by zifeiyue** [comment]
我也同样遇到了这个问题，CentOS Linux release 7.6.1810 (Core) ，大概是判断系统的语句有问题。
如果确认是centos 7 没问题，将 https://git.io/fNpuL 的文件down到你自己的主机上，修改：
echo "你的操作系统不受支持，请选择在 Ubuntu/Debian/CentOS 操作系统上安装！"
exit 1
为：OS='CentOS'

已经测试通过

**Comment by leitbogioro** [comment]
我的脚本里判断条件里，满足“非 Cent OS”系统的条件是：1. “etc”文件夹里不存在“redhat-release”文件，2. 在满足“1”条件的情况下，“redhat-release”文件里，没有“CentOS”关键字，3. Cent OS 的版本不得低于 Cent OS 6。除此之外没有任何专门判断 CentOS 7的逻辑。
建议您仔细排查以上目录和文件是否满足条件，因为正常的纯净 CentOS 系统都包含这些条件

**Comment by zifeiyue** [comment]
我也出现了这种情况，并且系统的确是CentOS 7.
![image](https://user-images.githubusercontent.com/46803713/55716865-9cf5ee00-5a2a-11e9-91f4-33fae3953e1d.png)

**Comment by leitbogioro** [comment]
是我的锅，问题已解决，可以安装了
