### ISSUE TITLE
脚本存在问题 script have some problem

### ISSUE THREAD

**Issue by zbljz98** [leitbogioro/SSR.Go#19]
centos第一次运行脚本提示不是centos的系统
系统的shell我换成了zsh了，不知道是不是这个问题

脚本中的检测进程逻辑存在问题
ps aux | grep 'aliyun'这样始终都会有返回的，因为有一个grep的进程，需要用grep -v先排出才行

**Comment by zbljz98** [comment]
服务器没有更换zsh还是bash

我删掉了检测系统和软件的逻辑部分正常安装

**Comment by leitbogioro** [comment]
我目前在用搬瓦工的纯净 Debian 9 环境，全新安装没有问题，在 CentOS 6 和 Cent OS 7 环境上也测试过了，完全没问题，建议您自行排查您环境是否纯净，系统变量的配置是否正确

**Comment by leitbogioro** [comment]
虽然你在命令行里直接运行 ps aux | grep 'aliyun' 这种的，即使没有阿里云的进程，也会排出类似 “root      2204  0.0  0.1  12780   984 pts/0    S+   03:38   0:00 grep aliyun” 这样的查询进程，但这个进程在执行完刚才第一个命令中的 “grep 'aliyun' ”副命令并打印出结果后，就立马终止了。也就是说当 ps aux | grep 'aliyun' 被当做 if 判断条件时，如果系统内没有已在运行的，名为 “aliyun” 的进程时，if 判断式已检测到相关条件并不符合系统里存在 “aliyun” 进程的逻辑，就不会终止，那个执行后打印的结果不会影响到脚本逻辑的判断。

**Comment by leitbogioro** [comment]
另外，我的脚本里判断条件里，满足“非 Cent OS”系统的条件是：1. “etc”文件夹里不存在“redhat-release”文件，2. 在满足“1”条件的情况下，“redhat-release”文件里，没有“CentOS”关键字，3. Cent OS 的版本不得低于 Cent OS 6。
适配系统是一件很复杂的工作，尤其是发行版各异的 Linux 系统，限定可用的系统，目的是我只在这些主流系统上做过安装可能性、使用可能性的测试，没测试过的平台我当然不会贸然就给他们用。
就拿上面的例子，虽然师出同门，但 Redhat 系统就因为 bin 目录下文件的执行权限不好调整，暂时没做适配，而 Cent OS 没做这个限制，就做了适配。
脚本里判断系统版本的逻辑就是以上这么多，而且是最通行、最普遍的做法，如果你安装的发行版在任何以上我所说的，可供脚本做逻辑判断的文件里的内容有问题，都不能算是普遍情况，我也没有任何办法可以准确地预知这些发生概率只有 0.001% 的情况。
毕竟这不是商业作品，我也没有 100% 的精力去天天倾听很小一部分自己系统变量有问题的用户的需求，如果你觉得我的脚本的逻辑判断有硬伤，我这边自然会在我的环境上直接跑一遍试试，如果我并不能从你的反馈中获得任何有关于我这方面的错误，恕我没有办法去改正。

**Comment by leitbogioro** [comment]
你说的“第一次”运行，可能已经在上面配置了各种其他环境，甚至我都不知道你 CentOS 的版本，代理服务器就应该是专用的，不要和生产环境混杂在一块。
擅自更改最“通用”的系统环境变量，或是自己的系统版本条件根本就与脚本逻辑不和，这些问题我是真没法帮您解决，而且您指出来的我的逻辑判断问题也不成立，这样因为沟通不畅，把双方都弄得心情不爽，不太好吧。

**Comment by leitbogioro** [comment]
是我的锅，问题已解决，请重新安装

**Comment by zbljz98** [comment]
谢谢您的指正，学习了。
环境是新的，反复重装，可能确确实实系统变化较大。

在 2019年4月8日，15:30，Molly Lau <notifications@github.com<mailto:notifications@github.com>> 写道：


我目前在用搬瓦工的纯净 Debian 9 环境，全新安装没有问题，在 CentOS 6 和 Cent OS 7 环境上也测试过了，完全没问题，建议您自行排查您环境是否纯净，系统变量的配置是否正确
