### ISSUE TITLE
/etc/init.d/shadowsocks脚本好像有点问题。

### ISSUE THREAD

**Issue by mclovin-2k** [leitbogioro/SSR.Go#2]
不管是status还是restart，都会报too many arguments。

root@localhost:/# etc/init.d/shadowsocks status
etc/init.d/shadowsocks: line 26: [: too many arguments
ShadowsocksR is stopped

root@localhost:/# etc/init.d/shadowsocks restart
etc/init.d/shadowsocks: line 26: [: too many arguments
ShadowsocksR is stopped
etc/init.d/shadowsocks: line 26: [: too many arguments
IPv6 support
2017-12-02 10:48:24 INFO     shell.py:74 ShadowsocksR 3.4.0 2017-07-27
2017-12-02 10:48:24 ERROR    daemon.py:75 already started at pid 293
Starting ShadowsocksR failed

**Comment by leitbogioro** [comment]
我这儿试了，没问题的
