### ISSUE TITLE
千万别用443端口

### ISSUE THREAD

**Issue by yinzheng-zhong** [leitbogioro/SSR.Go#5]
就是想提醒下，用443端口不管用什么混淆，VPS几乎被秒杀，直接封IP。我试了好几个VPS都是如此，后来换成10000以上的端口，我这个日本VPS用了快8个月没被封，香港的用了块半年。

**Comment by leitbogioro** [comment]
好的，我会更新脚本的判断逻辑，不再默认使用443端口

**Comment by x0r2d2** [comment]
@zxhaxdr 
Could you please share your SSR server config?
Thanks.

**Comment by yinzheng-zhong** [comment]
@hybtoy 
Port: 12300 (actually I think any port greater than 10000 is fine)
Key: ********
Encrypt Method: none
Protocol: auth_chain_b
Obfs: tls1.2_ticket_auth

I used port 443 in the early time but the longest surviving time for the VPS was less than one month. After I changed the port, none of my VPSs was banned till now (I have 4 VPSs and no one dies, except one VPS's TCP connection was banned by China Mobile because I'm sharing this one with my friends).
