### ISSUE TITLE
Default parameters are not applied

### ISSUE THREAD

**Issue by x0r2d2** [leitbogioro/SSR.Go#6]
Hello, 

Just tried to install SSRR with default parameters that are shown during installation but by the end I received this setup:

Congratulations, ShadowsocksRR server install completed!
Your Server IP        :  blah-blah-blah
Your Server Port      :  19085
Your Password         :  password
Your Protocol         :  origin
Your obfs             :  plain
Your Encryption Method:  aes-256-cfb

Do you need setup log file?

**Comment by leitbogioro** [comment]
Hey man, the last setup tells you that the configuration of ShadowSocksRR, it certainly different from settings of shell after tested. Settings I had ordered in shell should be these:

Congratulations, ShadowsocksRR server install completed!
Your Server IP : something IPv4
Your Server Port : XXXXX
Your Password : MollyLau
Your Protocol : origin
Your obfs : plain
Your Encryption Method: aes-256-cfb

Waiting for me to fix it right!

**Comment by leitbogioro** [comment]
It fixed.
