### ISSUE TITLE
一些小Bugs

### ISSUE THREAD

**Issue by littleplus** [leitbogioro/SSR.Go#8]
1、装完以后显示请运行srr
2、运行以后某个流程显示ssrr（忘了是哪里了，好像是停止/启动服务的时候）
3、修改密码的时候选n也会继续修改密码

**Comment by leitbogioro** [comment]
1. 第一个没问题
2. 第二个，这个项目确切地讲，应该叫“shadowsocksrr”，因为原项目破娃酱已经不再维护了，新的作者就叫它这个，想改当然也是可以的
3. “是否随机生成一个新密码（y/n）”的潜台词是：如果不需要生成一个随机密码，那么我会把设置密码的主动权交给用户，保证配置的灵活性

**Comment by leitbogioro** [comment]
1. 第一个已修正
2. 第二个，这个项目确切地讲，应该叫“shadowsocksrr”，因为原项目破娃酱已经不再维护了，新的作者就叫它这个，想改当然也是可以的，我去新版的 SSR 安装包里调整一下
3. “是否随机生成一个新密码（y/n）”的潜台词是：如果不需要生成一个随机密码，那么我会把设置密码的主动权交给用户，保证配置的灵活性

**Comment by x0r2d2** [comment]
It will be only on Chinese or you plan to translate it to English also?

**Comment by littleplus** [comment]
@hybtoy I think you mean in Chinese, right?
