### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by youngda** [leitbogioro/SSR.Go#9]
请选择： 1

1.启动服务
2.停止服务
3.重启服务
4.运行状态
5.运行日志

请选择： 1

Traceback (most recent call last):
  File "/usr/local/shadowsocks/server.py", line 32, in <module>
    from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, \
  File "/usr/local/shadowsocks/../shadowsocks/tcprelay.py", line 32, in <module>
    from shadowsocks import encrypt, obfs, eventloop, shell, common, lru_cache, version
  File "/usr/local/shadowsocks/../shadowsocks/obfs.py", line 39
    return {"auth_aes128_md5", "auth_aes128_sha1",
                             ^
SyntaxError: invalid syntax
Starting ShadowsocksR failed
ssrr服务启动成功！

**Comment by leitbogioro** [comment]
已修正，重新安装试试

**Comment by x0r2d2** [comment]
@leitbogioro 
Will you translate the options to the English?

**Comment by leitbogioro** [comment]
Emmm……I have this plan, wait for me to translate it.

**Comment by youngda** [comment]
@leitbogioro 

3
该协议已不可抵御防火长城的重放攻击，不建议使用，是否要选择？(y/n)
y
新的协议为：auth_sha1_v4
ShadowsocksR is stopped
Traceback (most recent call last):
  File "/usr/local/shadowsocks/server.py", line 32, in <module>
    from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, \
  File "/usr/local/shadowsocks/../shadowsocks/tcprelay.py", line 32, in <module>
    from shadowsocks import encrypt, obfs, eventloop, shell, common, lru_cache, version
  File "/usr/local/shadowsocks/../shadowsocks/obfs.py", line 39
    return {"auth_aes128_md5", "auth_aes128_sha1",
                             ^
SyntaxError: invalid syntax
Starting ShadowsocksR failed

传输协议配置已完成！

**Comment by youngda** [comment]
是不是我系统问题？搬瓦工官方centos6

**Comment by leitbogioro** [comment]
在Ubuntu上测试未发现问题，我切换到CentOS 6环境试试看，强烈推荐Ubuntu 16.04环境

**Comment by leitbogioro** [comment]
@hybtoy English version of SSR.Go is released, please input 
bash -c "$(curl -fsSL https://git.io/fAU32)"
and then press enter to install.

**Comment by leitbogioro** [comment]
@hybtoy English version of SSR.Go is released, please input
bash -c "$(curl -fsSL https://git.io/fAUCt)"
and then press enter to install.

**Comment by leitbogioro** [comment]
@youngda 经查明，是 ssr 源代码的语法错误，从主程序中的 obfs.py 文件内的第 39 行开始返回的协议列表，应当用列表（List）—— [] 括起来，而不是用字典（Dictionary）—— {}，以上造成了CentOS环境下的运行错误，我去修改一下源代码，稍后重新打包上传

**Comment by youngda** [comment]
@leitbogioro 好的谢谢啦

**Comment by leitbogioro** [comment]
没啥问题了哈，没问题我关贴了。

**Comment by youngda** [comment]
缺了两个包wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install qrcode
pip install Image
